# Generated by Django 3.0.6 on 2020-05-26 11:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_name', models.CharField(max_length=50)),
                ('exception_value', models.CharField(max_length=250)),
                ('exception_tb', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
