# Generated by Django 3.0.5 on 2020-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Закупка'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Продажа'),
        ),
    ]
