# Generated by Django 3.0.6 on 2020-05-07 10:12

import cafe.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20200430_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поставки'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('image_base64', models.TextField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe.Product')),
            ],
            bases=(cafe.models.Base64ImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='categories/%Y/%m/%d/')),
                ('image_base64', models.TextField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe.Category')),
            ],
            bases=(cafe.models.Base64ImageMixin, models.Model),
        ),
    ]
