# Generated by Django 3.0.6 on 2020-05-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20200507_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='destructioningredient',
            options={'verbose_name': 'Списание продукта', 'verbose_name_plural': 'Списание продуктов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productingredient',
            options={'verbose_name': 'Технологическая карта', 'verbose_name_plural': 'Технологические карты'},
        ),
        migrations.RenameField(
            model_name='categoryimage',
            old_name='product',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_chart', to='cafe.Ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_chart', to='cafe.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='value',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='cafe.Ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='cafe.Shipment', verbose_name='Ингридиент'),
        ),
    ]
