# Generated by Django 3.0.6 on 2020-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20200513_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ('id',), 'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'get_latest_by': 'date', 'ordering': ('date',), 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
    ]
